#!/usr/bin/python3

#(doc-id+word, 1)
import sys
import string
import os

for line in sys.stdin:
    docid_word, count = line.strip().split("\t")
    docid, word = docid_word.strip().split("+")
            #k = doc_id+"+"+filtered    
    print('%s\t%s\t%s' % (docid, word,count))

